/*
 * generated by Xtext 2.25.0
 */
package org.xtext.workout.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMyDslScopeProvider extends DelegatingScopeProvider {
}
